---
- name: Configure nginx web server 
  hosts: webserver
  become: yes # to be sudo when want to install 
  tasks:
  - name: install nginx server
    apt:
      name: nginx 
      # name: nginx:version we want or use regular expression 
      state: latest
      # state: absent to uninstall the package
      # state: present when define the version
  - name: start nginx server
    service:
      name: nginx
      state: started
      # state : stopped
  