---
- name: Configure nginx web server # is play name and every play has to have hosts
  hosts: webserver
  become: yes # to be sudo when want to install 
  tasks: # list of jobs that we want to run on hosts
  - name: install nginx server # give name whatever you want
    apt: # it's module which is specific command that we want to execute 
      name: nginx 
      # name: nginx:version we want or use regular expression 
      state: latest
      # state: absent to uninstall the package
      # state: present when define the version
  - name: start nginx server
    service:
      name: nginx
      state: started # server should be started
      # state : stopped
  